volumes:
  mongo_data:
    driver: "local"

networks:
  postgres_compose_network:
    driver: "bridge"

services:
  mongodb:
    image: mongo:latest
    container_name: database_wise_notification_compose
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_wise_notification_compose
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/wise-notification?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    links:
        - mongodb
    networks:
      - postgres_compose_network