version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: notification_wise_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}

  rabbitmq:
    image: rabbitmq:3.9-management # todo - validar se habilito a interface
    container_name: notification_wise_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser # Set default username
      - RABBITMQ_DEFAULT_PASS=mypassword # Set default password.  **IMPORTANT: Change this in production!**

volumes:
  mongo_data:
    driver: "local" # todo - validar
  rabbitmq_data:
    driver: "local" # todo - validar

networks:
  notification_wise_network:
    driver: "bridge"


#  backend:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: backend_wise_notification_compose
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/wise-notification?authSource=admin
#    depends_on:
#      - mongodb
#    ports:
#      - "8080:8080"
#    links:
#        - mongodb
#    networks:
#      - notification_wise_network