version: '3.7'

networks:
  notification_wise_network:
    driver: "bridge"

volumes:
  mongo_data:
    driver: "local"
  rabbitmq_data:
    driver: "local"

services:
  mongodb:
    image: mongo:latest
    container_name: notification_wise_mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - notification_wise_network
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: notification_wise_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notification_wise_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=GRaPHerf
      - RABBITMQ_DEFAULT_PASS=xcU204QDLk2@

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: notification_wise_backend
    restart: on-failure
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8084:8084"
    networks:
      - notification_wise_network